# Generated by Django 5.1.2 on 2024-12-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_comment_is_approved'),
        ('myapp', '0003_alter_post_published_at'),
    ]

    operations = [
    ]
